### PR TITLE
Macrotime.0.2

### PR DESCRIPTION
**Pull request by frickler24**
Hello,
this branch for improving the macro properties involves three things:
1. Handling of different delays when playing macros (ccMSC/ckb#437)
2. A GUI for recording the time between keystrokes during recording
3. The branch is based on my last pullrequest "K95 rgb v205 init bug" #24 

For users which have used G-Keys with complex definitions, there is a short shell script  to convert existing definitons into the new form (migmac.sh)

It has been tested on linux mint 18/64 with K95RGB and M65

### CODE REVIEW

**Comment by frickler24** [comment]
I added the GUI improvements from #124 onto the PR. Because of incompatibilies between #124 and this one, it work for me. Please test against the resizing / cutting issues when integrating in the testing branch in 0.2.9.

**Comment by ghost** [comment]
Well, I marked it for 0.2.9 just so that we merge at it at most before 0.2.9 :). Thus if people have time to test this, it can be merged instantly (as usual, after at least two collabs have checked it).

**Comment by tatokis** [comment]
There seems to be an issue with this. Whenever a macro is being typed with delay, the animations freeze.

**Comment by frickler24** [comment]
@tatokis Thank you for the issue, I found the critical section. 
But if I change it so that the lightning is unblocked while macro player is sleeping, we get an error if you press another macro-Key while the playing is still running.
I have to think about it again.

**Comment by frickler24** [comment]
@tatokis  this issue was really hard to fix. Please try again if you have time for it.
@stephenhouser, @fleischie and others running macOS, please try the last commit if you like.

I messed up the git history for this branch a bit, so the latest commit should contain elements for the new firmware mechanism also. I'll fix it if the function is ok.

**Comment by tatokis** [comment]
Pressing a macro key no longer types anything.

**Comment by tatokis** [comment]
Ignore the above message, I had the wrong ckb-daemon started. It's working as expected now. I think this should finally be merged.

**Comment by tatokis** [comment]
@frickler24 Since both of us have confirmed it working, could you please close this PR and reopen it with only the relevant commits (against testing if you do it before the 20th).
I want this to be merged ASAP.

**Comment by frickler24** [comment]
OK

**Pull request closed without merging**
