### PR TITLE
AUR Package

### PR DESCRIPTION
**Pull request by makz27**
Hello,

I submitted a new AUR package for your ckb fork.

I cloned the original ckb-git package and changed the source.

This package has been tried on a new installation it work like a charm.

If you think it need more dependencies send me your feedback i'll update the package as fast as possible.

Thank to next-team for maintaining this project up to date :)

### CODE REVIEW

**Comment by ghost** [comment]
I was going to create a new one based on cmake. When it's ready, would you be able to maintain it (because the name is taken)?

**Comment by makz27** [comment]
I pushed the -latest- version too and added you as co-maintainer for both packages.

**Comment by ghost** [comment]
I thought it's not possible. Great, thanks. Let this be just for now, I'm going to finish cmake support in a short period of time. It also interconnects with Readme changes - new names, new instructions, document restructures. Would you mind moving onto cmake at some point?

**Comment by makz27** [comment]
Yeah no problems.

**Comment by ghost** [comment]
Cool, thanks again for pushing at least what there's available now.

**Pull request merged**
