### PR TITLE
New approach fixing97 (looking for wrong firmware on currrent devices)

### PR DESCRIPTION
**Pull request by frickler24**
This PR replaces #155 and is the new approach to solve issue #97.
@tatokis, @bulletmark and anyone who has new hardware, has trouble with #97 and is able to act if there is still ab bug in this PR, might test. How to test is mentioned in the last commit.

**Read the information in the panels carefully - you are dealing with the firmware of your devices.**

Please give feedback about your test result:
- What productID, 
- version_from, 
- version_to, 
- was it just a "fake" by changing the fwversion-file or a real update?
- and your result

Thanks in advance.

**Important for the maintainers:** 
This version is referencing the FIRMWARE file from my repo because of the incompatible file format 
(the FIRMWARE file is signed by tatokis, so it is safe for testing).
We have to change two lines before we merge it into master or testing branch.

### CODE REVIEW

**Comment by SethBarberee** [comment]
Is it possible to add Scimitar Pro RGB into the table? This should fix the my issue #229 where Scimitar Pro was detected as a normal Scimitar. 

Product ID: 0x1b3e
Version from CUE: v1.1

**Comment by frickler24** [comment]
@SethBarberee I'll have a look tomorrow on it. Do you know what the version of your current firmware file could be (I tried over a thick thumb with https://www3.corsair.com/software/HID/ScimitarPRORGB.zip and got a hit; Version 1.10 was ready for download):
grafik

**Comment by SethBarberee** [comment]
Mine is currently v1.1. The same as CUE. I've just been updating it in CUE

**Comment by frickler24** [comment]
@tatokis or @mattanger could you please sign the FIRMWARE file in this branch?
Thanks.
Some time ago @tatokis and I discussed how to handle the incompatible file formats in FIRMWARE between the old and new implementation. The last commitment was to ignore the older running ckb implementations for a better readability of the new FIRMWARE file format.
What do you think about renaming the new FIRMWARE file, eg to FIRMWARE8?
The we can leave the older version some time as it is and avoid issues like "firmware download broken".

**Comment by ghost** [comment]
Regarding 

> since ckb would no longer be able to find the right device, it should not prompt for an update at all

from https://github.com/mattanger/ckb-next/issues/229#issuecomment-308000934:

We might want to write a notice somewhere near the update button with the button greyed out, that automatic updates for this device are not supported, or something like that.

**Comment by ghost** [comment]
As a simple solution based on how it's currently implemented, the text on the button could be "Unsupported" (instead of "Up to date") and pressing the button would yield the above-mentioned notice instead of "Your firmware is already up to date".

**Comment by ghost** [comment]
Regarding this PR.

Strafe RGB 2.05, manually downgraded `fwversion` to `0200` and immediately got a proposition to update when starting GUI. I thought it would reflash v2.05, which it most probably did, according to GUI, but at some point a pthread error happened (might be an issue with `pthread_cancel()` or `pthread_join()` logic?) and the keyboard is in a bootloader mode right now. Logs:
```console
# nvim /dev/input/ckb1/fwversion
$ ./bin/ckb &|
Path  to settings is "/home/l2y/.config/ckb/ckb.conf"
Scanning  "/usr/lib/ckb-animations/ckb-gradient"
Scanning  "/usr/lib/ckb-animations/ckb-heat"
Scanning  "/usr/lib/ckb-animations/ckb-mviz"
Scanning  "/usr/lib/ckb-animations/ckb-pinwheel"
Scanning  "/usr/lib/ckb-animations/ckb-rain"
Scanning  "/usr/lib/ckb-animations/ckb-random"
Scanning  "/usr/lib/ckb-animations/ckb-ripple"
Scanning  "/usr/lib/ckb-animations/ckb-wave"
Downloaded new firmware list. 11 entries found.
[I] Loading firmware version 0205 from /tmp/ckb-4196-fwblob.bin
[I] Firmware update complete
[I] Stopping input thread for /dev/input/ckb1
[I] Disconnecting /dev/input/ckb1
[I] Removed device path /dev/input/ckb1
QThread::start: Thread termination error: No such process
```
This is where the error happens, right after the flashing process seemed to be done (reached 100%). Note that I launched ckb-daemon and ckb on the same console, so I cannot tell exactly whether this error belongs to ckb or ckb-daemon. However, considering the logs afterwards, it's most probably a ckb-daemon error. But in this case, I guess, it should've written a line where it has happened. It didn't, so I suppose we don't check for this error.

Logs after it:
```console
[I] >>>vendor = 0x1b1c, product = 0x1b20, path = /dev/bus/usb/003/014, syspath = /sys/devices/pci0000:00/0000:00:14.0/usb3/3-4
[I] Connecting Corsair STRAFE RGB Bootloader at /dev/input/ckb1
[I] claiming interfaces. name=Corsair STRAFE RGB Bootloader, serial=0E024015AEAA1003550E6848F5001940, firmware=0014; Got >> 4<< as ep_str
[I] claiming 4 endpoints
[I] Starting input thread for /dev/input/ckb1
[E] os_sendindicators (usb_linux.c:220): Connection timed out
[I] Attempting reset...
[E] os_resetusb (via usb.c:470): resetusb failed: No such device
[E] usb_tryreset (usb.c:478): Reset failed. Disconnecting.
[I] Stopping input thread for /dev/input/ckb1
[E] os_usbsend (via firmware.c:15):  No such device, res = 0xffffffff
[W] _start_dev (device.c:41): Unable to load firmware version/poll rate
[I] Setup finished for /dev/input/ckb1
[I] Disconnecting /dev/input/ckb1
[I] Removed device path /dev/input/ckb1
```
and this part of the log just loops. So, something was wrong during flashing.

I guess that this is not an expected behavior as it's not a downgrading or something dangerous, it's just a reflash of the same 2.05 version.

I'll try force-reflashing the keyboard with CUE. If you know how to recover from bootloader mode (manually, as it's impossible through ckb GUI) under Linux/OSX, please write a wiki article so that it's used for the great good.

UPD1. Keyboard was rescued through CUE.

UPD2. This might be a longstanding issue not really related to this PR, as I've never attempted to update the keyboard with ckb IIRC. I suggest moving the discussion on exactly this error into a new issue - #235.

**Comment by SethBarberee** [comment]
I'll have some time tomorrow so I'll test the PR with my Strafe RGB and Scimitar PRO. I'll probably just edit this comment and put the results here.

EDIT:
Scimitar PRO at v1.1 when I click check for updates
```"Can't find valid firmware version for device 6974 "6974"```

Strafe RGB manual downgrade by editing `fwversion` to 2.04 and upgrading to 2.05:
Worked fine. Dialog came up to upgrade and flashed perfectly fine

**Comment by SethBarberee** [comment]
Finally got around to testing PR with my Strafe RGB and Scimitar Pro. I edited my previous comment with the results.

**Comment by tatokis** [comment]
Since this got accidentally deleted, @frickler24 would you be willing to reopen it against master? We really need this ASAP.

**Pull request closed without merging**
