### PR TITLE
Feature/daemon dialog

### PR DESCRIPTION
**Pull request by fleischie**
This PR implements a dialog box, that shows the user, that the daemon is not running and how to (probably) fix this issue themselves.

It currently only checks, whether the daemon has created the `/dev/input/ckb0` or `/var/run/ckb0` paths for linux respectively mac and shows the dialog with either instructions for systemd or launchctl.

NOTE: This does not check for the actual daemon to run, as I am not quite sure, whether it's worth the effort (check file for readability, check contents of file, test process to run by pid). Also it does not check for upstart/non-launchctl methods.

Feedback welcome. :smile:

### CODE REVIEW

**Review by ghost — APPROVED** [review]
This is something that should have been there since forever. Good job!

**Comment by ghost** [comment]
Additionally, I've cherry-picked the macOS fix so that one can compile this on macOS and made the dialog unskippable - one has to press OK before interacting with the main window.

**Review by Ravenslofty — CHANGES_REQUESTED** [review]
Can you rebase this @fleischie? I think this might be overwriting things like the qmake workaround and the mac deployment target,

**Comment by fleischie** [comment]
Yeah, I can rebase. I'll be available at monday/tuesday or something.
Either we discuss this live on irc or you give me a hint, what to rebase onto where and when. 😉

**Comment by fleischie** [comment]
Hey @light2yellow @ZirconiumX I rebased the branch onto master and force pushed (be advised). I didn't have time to test it yet on Mac, will do so tomorrow.

**Comment by ghost** [comment]
I did. It's OK.

**Review by Ravenslofty — APPROVED** [review]
Let's get this merged in.

**Pull request merged**
