### PR TITLE
Clarify macOS Installation Instructions

### PR DESCRIPTION
**Pull request by tbcrawford-old**
This reminds the developer or user to ensure that Xcode command line tools are installed as well as updating to the macOS name which started with macOS Sierra.

### CODE REVIEW

**Comment by fleischie** [comment]
Regarding the OS name: Is there a further difference, than renaming `OS X` to `mac OS`? I'm worried, that the new name hase some implications as to the previous versions of OS X (pre-Sierra).

Or to put it differently: Would it make more sense to have it say "OS X/macOS".

**Comment by mattanger** [comment]
I wasn't even aware that the name was officially changed. I think something along OS X/macOS as @fleischie  suggested would be the most appropriate. I guess the old versions are still OS X?

**Comment by ghost** [comment]
> The current Mac operating system is macOS, originally named "Mac OS X" until 2012 and then "OS X" until 2016.

Not sure if we need to care...

**Comment by mattanger** [comment]
I don't really care. I guess it doesn't hurt to be as clear as possible though.

**Comment by tbcrawford-old** [comment]
I can update this to remove that change specifically and revert it back to OS X, or we could go with OS X/macOS like some have stated. I just thought by renaming OS X to macOS in the README it would accurately reflect the current name of Apple's desktop OS.

**Comment by fleischie** [comment]
`macOS and previously` or `OS X and later` preferably with an exact version number would also work. 😃

The main issue is the problematic Sierra support, which needs to be addressed in the near future. An unspecific description might be more harm than good, as different versions might need different installation/setup/feature descriptions. So if you want to update the PR - which I personally would prefer very much - be as specific as possible with the Mac OS versions. 🙏

**Comment by tbcrawford-old** [comment]
Sounds good. What issues still need addressed on Sierra by the way? I do believe `OS X and later` would primarily encompass `OS X/macOS`. @mattanger seemed to be ok with `OS X/macOS` which should bring anyone in using either of the two terminologies and even if someone is using `Mac OS X` terminology, this project should be able to be found as well I do believe. 

I apologize, I did not mean for this to cause such a discussion and I hope that is is not taking focus away from other parts of the project.

If you guys are all okay with `OS X/macOS` I will go ahead and update that as soon as I can.

**Comment by fleischie** [comment]
@tbcrawford I specifically refer to the key-binding issues with Sierra. But I guess it's something for another issue. 😄

That sounds good. The more we all are content with what we're introducing into the project the better. 😊

**Comment by tbcrawford-old** [comment]
Ah yes. I did see that was an issue! I have updated my branch for more clarity.

**Pull request merged**
