### PR TITLE
fix DPI cycling

### PR DESCRIPTION
**Pull request by pjcv**

### CODE REVIEW

**Comment by ghost** [comment]
Please describe what you did, what was the behavior previously, what would the PR change and how to test it. Best place for this information is the commit message but since you didn't provide it there, you can still do this here.

**Comment by pjcv** [comment]
This would change all DPI Up/Down to cycle through the DPI stages, which mimics the hardware behaviour of some (?) mice, allowing all DPI stages to be reached with a single button.

If we wish to retain the current behaviour of capping the stage on Up and Down, then perhaps it makes sense to add new bindings specifically for the cycling behaviour.

**Comment by pjcv** [comment]
I've implemented the behaviour I suggested in my previous comment. Cycling the DPI up is now the default for the DPI button on the Glaive and the Harpoon.

I've also corrected some (presumably Glaive-specific) issues with the DPI LEDs, please see my branch "lazydpi" for those fixes. I can submit that branch as a PR if you like, with it I think Glaive support #225 would basically be complete.

**Review by tatokis — APPROVED** [review]
Looks good to me.

**Review by ghost — APPROVED** [review]

**Pull request merged**
