### PR TITLE
mouse related macro recording 

### PR DESCRIPTION
**Pull request by frickler24**
This PR should solve #121.

### CODE REVIEW

**Review by tatokis — CHANGES_REQUESTED** [review]
I didn't detect any regressions, however, I think we need to hide the extra debugging info before merging.

Ideally, we should (if we don't already), hide it all under a preprocessor DEBUG if.

**Comment by frickler24** [comment]
@tatokis I understand your point. IMHO we should implement a convenient way to control debug info at runtime, not at compile time. This would help users to give us logging info in case of new functions or issue handling.
So what about a CLI parameter "--debug \<level\>", with a number to define debug level.
Or an environment value CKBNEXTDEBUG=\<level\> or a number at the settings page in the gui?

**Comment by ghost** [comment]
> IMHO we should implement a convenient way to control debug info at runtime, not at compile time.

Good idea. However, this is just another story not really related to the feature introduced by the PR. As far as I'm concerned sending stuff to qDebug() is done all over the program, so I'd propose opening another issue regarding changes in all files and not this particular PR (just for now, until it's merged).

Regarding the commits, I haven't test them myself yet, so I cannot leave a comment specifically on them. However, in my opinion it shouldn't be blocked because of the way debugging is handled.

**Comment by LivingWithHippos** [comment]
@frickler24 doesn't work, the keys are not recorded, they appear typed normally (what I press is written normally inside the mactoText)

```
Features = "corsair scimitar rgb pollrate adjrate bind notify fwversion fwupdate"
No Keyboard detected, leaving macroPath as is: "" and macroNumber as -1
Downloaded new firmware list. 12 entries found.
"No cmd or valid handle for notification found, macroNumber = -1, lastCmd = "
MacroReader::run() started with -1 and "" and QPlainTextEdit(0x1b3a2a0, name = "pteMacroBox") and QPlainTextEdit(0x1b45590, name = "pteMacroText")
trying to open notify-File "/notify-1"
unable to open macroFile "/notify-1"

```

Maybe It should be notify1?

**Comment by frickler24** [comment]
@LivingWithHippos No, it should be notify2 or 3, but the problem is, that it does not detect your system as a keyboard ("No Keyboard detected..."). So it does not set the path to /dev/input/ckb1.
The question is: Why does the corresponding function give me a false indication?
I'll have a look at it in ca. 2 hours. Maybe I need your help again for more debugging infos.

**Comment by ghost** [comment]
Well, I just realized that I cannot really test this not only for the absence of mouse, but because the buttons in the whole "Binding" widget are unreachable no matter how stretched the GUI is (see the picture). For those who experience the same issue but still would like to test the PR there's another PR - #131 - that you will need to merge into this one, manually (for example, by adding the upstream (e. g. this repo) as a remote, checking out a specific remote branch and cherry-picking). There's that.

screenshot_20170411_125502

**Comment by frickler24** [comment]
@LivingWithHippos Do you have a corsair keyboard attached to your system (one that is serviced by ckb-next)? Or just a mouse?
If you do not have a ckb-next-compatible keyboard, you can't record macros by typing!
This is because the keys you record must come from a ckb-next driven keyboard-channel. 
No other input channel is now or will later be implemented.

so without a ckb-next keyboard you may record the macros by hand and import them with cut&paste into the "Macro Key Actions" panel ans save them by clicking Apply.

**Comment by tatokis** [comment]
It shouldn't be difficult to implement key capturing on linux with xcb, macOS is another story though.
Perhaps we can use a Qt textbox to do it, so that it's cross platform.

**Comment by frickler24** [comment]
The task is to translate the characters we get from another keyboard into the +/-keyname values for ckb. Not a problem for a standard layout, but I think we need configuration depending on different KB-layouts, language special chars etc. Don't know if we really want this yet.

**Comment by tatokis** [comment]
@frickler24 Agreed. And we do need to keep in mind that the daemon has no concept of layouts, they are all implemented in the GUI.

**Comment by frickler24** [comment]
What we might think about is a separate tool, showing a standard KB layout (as in the binding tab)
and some clever input methods: 
Typing, clicking meta-keys with on/off and in combination to each other and in combination with character input again. 
All will be translated into the keycode sequences needed by the deamon (is d**ea**mon right? I'm confused with the germean D**ä**mon which you can spell d**ae**mon also...).
All key mappings and the frame for the UI are in the ckb client. Not too much investigation will be needed for this project.
And then copy&paste the result into the macro binding tab for the mouse.
This may help users owning a ckb compatible mouse, but no KB.

**Comment by tatokis** [comment]
@frickler24 I just realised.
If the owner doesn't own a KB, then ckb-daemon will not register a virtual keyboard using uinput, so it won't be able to send keystrokes to the rest of the system.

EDIT: It's d**ae**mon

**Comment by frickler24** [comment]
@tatokis and @light2yellow I did some experiments with qDebug.
Since Qt 5.6 they implemented a verbosity-flag. Now you can
- decide which function you use (qDebug, qWarning, qCritical, qFatal)
- give a verbosity information with it:
```
qDebug().setVerbosity(7) << "This is a very critical issue and should be displayed in any case!";
qDebug().setVerbosity(0) << "If a user wants to read this stuff, he may select this.";
```
Standard Qt verbosity is 2.
In the next days I will post a skeleton how I think we may use this.
Like [this article](http://stackoverflow.com/questions/4954140/how-to-redirect-qdebug-qwarning-qcritical-etc-output#4954188) describes some aspects of it.
Or has someone experience with it?
As @light2yellow recommended, I open a new issue for this discussion.

**Comment by LivingWithHippos** [comment]
Yeah I'm on a laptop that's why I don't use another keyboard. I think implementing keyboard macro recording for the mouse shouldn't be too hard?  You can just take the keyboard input with http://doc.qt.io/qt-5/qwidget.html#keyPressEvent and http://doc.qt.io/qt-5/qwidget.html#keyReleaseEvent and rewrite them in the macro box with the plus and the minus in front of the key, I don't think you need to mess with localization and such, maybe if you don't find a corsair keyboard you could just create a default one with a special code to recognize it. Sorry if this is not feasible as I don't really know how to code for Qt

**Comment by frickler24** [comment]
Sorry, @LivingWithHippos, when we start such a development, I fear we get a lot of issues:
- the complete handling of modifier keys is definitely not handled by the way you describe
- yes, localization is a topic: It starts with pressing y on a german keyboard and getting +z,-z, from K95.
- what about loudness control, function keys and so on?

What you can is the following: We will give you a hint where to find the tables (which key is named how at linux /   macOS) in the source and you write a manual translation module and support us with it?

**Comment by LivingWithHippos** [comment]
@frickler24 I'll help but I'm not sure what you're asking me to do

**Comment by frickler24** [comment]
@LivingWithHippos This is the "right" answer for an open source project :-)

First question: Do you have implementation experience in
c / c++? scripting (Bash, sh, csh, tcsh or similar)? anything else (eg vba-macros)? 
Is it just Qt where you do not have knowledge about, concerning this project?

Depending on your implementation skills, we can choose a more complex (writing a script or gui program) or very manually but easy solution (based on paper+pencil).

**Comment by LivingWithHippos** [comment]
I just know java. I wrote a little script for sh, learnt a little c/c++ for a University exam and I made a script for vba on Excel. I'm looking to pick up a second language after java and I was thinking phyton but I'd have no problem studying something else. I guess a scripting language (sh or vba) would be easier and maybe more cross platform than c/c++

Edit: about this project I haven't looked at the source, I don't even know what language is used beside qt. I have no idea about how it works, I just backtracked my issue for the macroBox ;p

**Comment by frickler24** [comment]
OK, so let's think about a filter program in awk or bash + sed or what-else-we-need.
You can get a first idea what characters you have to handle in the following files:
- src/ckb-daemon/keymap.c:  const key keymap[N_KEYS_EXTENDED] = { ... (All keys available)
- src/ckb/keymap.cpp (Different layout types)
- src/ckb/keywidget.cpp: line 340 (with the "names" array for special names)
- src/ckb/rebindwidget.cpp: Line 21 (different groups of special keys to handle)
- search for ""lshift" to find more.

The idea: You write a macro text in your texteditor - all in one line.
If you need a special handling (eg press lshift+rshift and release them again), you notice this with 
`\+lshift\+rshift\-rshift\-lshift`  or in any other notation you define.
You should think about Control- and Meta-sequences - how to notate them? E.g. you cannot type CTRL-D into a script, because this means END-OF-FILE. 

Then you start your script (stdin+out +error should be enough for filehandling) and convert the content into the key-sequences:
a "normal" uppercase character into ,+\<key\>,-\<key\> with translating keys in the international area to the positional keys on the keyboard. Start with english, so the translation is 1:1 first :-)
a "normal" lowercase char into ,+lshift,+\<key\>,-\<key\>,-lshift with translating as above
a special element (eg \+lshift) into its representation

You know java, then you may have defined regular expressions. You'll need them here, because you will look for sequences which are longer than 1 character. Have a look at regexp-tutorials in the web, eg [this one](http://www.vogella.com/tutorials/JavaRegularExpressions/article.html).
You may define your algorithm in Java first - maybe this is the implementation at the end?

If you want to implementation in script form as mentioned above, you should have a look into awk-tutorials (but first read regexp...). awk is a block-interpreter for text-handling. 
If you have an idea, how 
- to struct your input sequences with and without special chars / keystrokes
- to build your reg-expressions

you start implementing the awk-script.

An alternative impression how you may use bash+sed (a stream-editor) I can give you here (the script does what it says in the starting comments and is understandable with knowledge of regexps also):
```
#!/bin/bash
SAVEFILE=~/.config/ckb/ckb.conf

###################
# 
# Change the format of macro definitons from 4- to 5-parts.
# 
#

# Find a line, beginning with '$macro:',
# followed by exact 3 colon-separated strings.
# The may not be a 4th string (it would be the new format).
# If found, add a ':x' at the end.
# Otherwise just print it.
SEDLINE='/$macro:[^:]*:[^:]*:[^:]*$/s/$/:x/'

cp $SAVEFILE $SAVEFILE.orig

# some statistics
echo -n "how many \$macro:-Statements to deal with: "
grep  "$macro:" $SAVEFILE | wc -l

echo -n "That number entries do we find: "
sed -e $SEDLINE $SAVEFILE | grep  "$macro:" | wc -l

echo -n "how many lines without \$macro:-statements: "
grep  -v "$macro:" $SAVEFILE | wc -l

echo -n "That many entries are ignored: "
sed -e $SEDLINE $SAVEFILE | grep -v "$macro:" | wc -l

read -p "Is the information correct? [y|n] " RL
RL=${RL:-n}

if [[ ${RL} != "y" ]]; then
    echo you typed $RL.
    echo "Aborted."
    exit -1;
fi

echo you typed $RL.
sed -e $SEDLINE $SAVEFILE > $SAVEFILE.new
rm -f $SAVEFILE
mv $SAVEFILE.new $SAVEFILE
wc $SAVEFILE
grep :x$ $SAVEFILE

exit 0
```

**Comment by LivingWithHippos** [comment]
Yeah luckily i know regex and I often use them here and there (lately on ketarin) I'll start coding something this evening, thanks for the tutorial

**Comment by LivingWithHippos** [comment]
@frickler24 when you wrote 

> a "normal" lowercase char into ,+lshift,+\<key>,-\<key>,-lshift
> a "normal" uppercase character into ,+\<key>,-\<key> 

did you mean the opposite?

**Comment by frickler24** [comment]
yes, sorry!

**Comment by LivingWithHippos** [comment]
@frickler24 I made something, give me your opinion https://github.com/LivingWithHippos/ckb-next_keyboard_macro_formatter . I have some questions, like how to translate symbols such as ! or ? since I can't find their code in ckb source code (I've hacked it for now).

**Review by tatokis — APPROVED** [review]

**Comment by frickler24** [comment]
Hi @LivingWithHippos , thanks, you've hit the idea pretty well.
A few suggestions for even more readable and maintainable code:
Insert some spaces intro your code line.
For example instead
`If(length($x)>1&&(substr($x,1,1)=="+"||substr($x,1,1)=="-")){macroLine=macroLine $x;break;}`
I'd rather write
`If (length($x) > 1 && (substr ($x, 1, 1) == "+" || substr ($x, 1, 1) == "-")) { macroLine = macroLine $x; break; }`
Some programmers spend even more spaces (I used to make, for example, between function names and parameter list, but with C ++ and Java I reduced that). 
I know that this is a "hot iron", especially the rules for setting brackets have already failed projects.

Since (except on line 2) you don't use regexp, you have to separate the characters in the input file by space. If you take the next step of recognizing longer strings, you can abbreviate this as you have already made in case of upper case chars.
But for your purposes the implementation is sufficient.

If you do a chmod 755 macro_script.sh, one can shorten the call to its name only (avoid calling sh explicitly).
To your question: Chars as "!" or "?" are the upper case version of their lower case keys.
So "!" is upper-case-"1" and "?" is (hope so, I'm sitting in front of a german keyboard) upper-case-"/". In keymap.c the KEYs are defined, not the CHARs. So have a look at your keyboard to find the other chars on the keys and you do not need to fix your implementation at UTF-8, as you have done with your "hack".

**Comment by LivingWithHippos** [comment]
@frickler24 I've cleaned it and added a DE filter. Just change the filter name in the macro_script.sh, can you test it? Is there a command to add a delay like in the CUE software? Because using too many symbols-> too many shift near each other bug ckb a little. I may try to optimize it this week

**Comment by frickler24** [comment]
@LivingWithHippos I'll have a look at weekend at it.
Delays are supportet if you install #25. Because it seems to be a bigger packet, It is marked as for release 0.2.9.

**Comment by frickler24** [comment]
@LivingWithHippos I've commented [in your repo](https://github.com/LivingWithHippos/ckb-next_keyboard_macro_formatter). We should use this thread for handling the PR only.

**Comment by LivingWithHippos** [comment]
@frickler24 I've taken a look, I'll code something later this week. If anyone is interested in this but is missing his layout (en, de and it for now), [there's a script here](https://github.com/LivingWithHippos/ckb-next_keyboard_macro_formatter/blob/master/scripts/automated_layout_filter_creator.sh) which can help you create easily a new layout for your language if you have a typical qwerty layout (I think I'll add a video because it's hard to explain but easy to do). I'll add new languages soon anyway

**Comment by frickler24** [comment]
When someone is rearranging our README.md, we may add a link to your repo for all users with Corsair mice but no Corsair KB.

**Comment by frickler24** [comment]
On hold until #152 is decided.

**Pull request closed without merging**
