### PR TITLE
New firmware file format

### PR DESCRIPTION
**Pull request by frickler24**
This new FIRMWARE file has some corrections (two devices have a newer firmware version)
and it gots an 8th element: The last entry is the ProductID the firmware line is designed to.
The handling of this new entry is added in the ckbfirmware cpp and headerfile.

@mattanger Please sign this FIRMWARE file and either send it to me or commit this pull request when signing the file (the firmware loading rejects the 8th element if you sign only and leave the old implementation).

Thanks!

### CODE REVIEW

**Comment by tatokis** [comment]
@frickler24 pushed it to your branch

**Comment by frickler24** [comment]
OK, Thank you.
This morning, I was frightened that this does not work. We would affect the download function of all existing ckb {, - next} installations, because they could not make any download from the FIRMWARE file (it would have 8 elements and the check for 7 would fail).

**Comment by frickler24** [comment]
I have a design question about dealing with FIRMWARE.
Yesterday I updated the file and added the ProductID for which the respective firmware is provided. However, this would have affected any reading of the existing ckb {, - next} installations.
Why? Each installation gets the current FIRMWARE file when Github is started. All previous installations expect 7 elements per line in the file, now it would have been 8 and there would have been only one error message, but no firmware test more.
So we need a new idea.

First I have checked whether we can misuse one of the existing fields by actually making two fields.
And yes, there is a way to do so: The field min.ckb can be divided into more than one field, because the reading function throws away all after a "+" sign.
With this we could change the file format to the following:

```
# Vendor  Model             FW   URL                                                        Min.ckb+PrID   File Name                    SHA256
  Corsair K70RGB            2.05 https://www3.corsair.com/software/HID/K70RGB.zip           0.2.7+0x1b13   K70RGB_APP_V205.bin          3e43bdcc5077dc413fbdee7ff6e57a978f758599142eef6979a96e3b8c3a566a
  Corsair K70LUX            2.04 https://www3.corsair.com/software/HID/K70LUX.zip           0.2.7+0x1b36   K70LUX_APP_V204.bin          c2b5411e1dce391788eca294563801b32a14bf7802eb29688213f8f07e112966
  Corsair K70LUXRGB         2.05 https://www3.corsair.com/software/HID/K70LUXRGB.zip        0.2.7+0x1b33   K70LUXRGB_APP_V205.bin       a1a0a4b2f74890eb708435b21ab197a301ea668269bca895f89f7301c354e83d
...
```
Not very nice, but compatible to all versions.

As another possibility, we could maintain two blocks in the file: the previous block with 7 elements and a new with 8. That would technically go, but is not very nice in the care.
But for this you could write a script or a calc-macro, which takes the (double) care for us.
The the file would look like this:
```
!BEGIN FW ENTRIES

# Vendor  Model             FW   URL                                                        Min.ckb File Name                       SHA256
  Corsair K70RGB            2.05 https://www3.corsair.com/software/HID/K70RGB.zip           0.2.7   K70RGB_APP_V205.bin             3e43bdcc5077dc413fbdee7ff6e57a978f758599142eef6979a96e3b8c3a566a
  Corsair K70LUX            2.04 https://www3.corsair.com/software/HID/K70LUX.zip           0.2.7   K70LUX_APP_V204.bin             c2b5411e1dce391788eca294563801b32a14bf7802eb29688213f8f07e112966
  Corsair K70LUXRGB         2.05 https://www3.corsair.com/software/HID/K70LUXRGB.zip        0.2.7   K70LUXRGB_APP_V205.bin          a1a0a4b2f74890eb708435b21ab197a301ea668269bca895f89f7301c354e83d
  Corsair K70RFIRE          2.05 https://www3.corsair.com/software/HID/K70RAPIDFIRE.zip     0.2.7   K70RAPIDFIRE_APP_V205.bin       6b1d2bb962ffd987ce5eb25c46b02a9069c5f79ca05d7b2cc71c749fe9813536
  Corsair K70RFIRERGB       2.05 https://www3.corsair.com/software/HID/K70RGBRAPIDFIRE.zip  0.2.7   K70RGBRAPIDFIRE_APP_V205.bin    a5962bd1d890f5061fcf242fa8d3ca806913f899f37585d4367420aaded25104
  Corsair K95RGB            2.05 https://www3.corsair.com/software/HID/K95RGB.zip           0.2.7   K95RGB_APP_V205.bin             8d0680dd033d6020a53bc9bfa83e761143699d1122f1d0133e95ad3056d63a15
  Corsair K95PLATINUMRGB    1.07 https://www3.corsair.com/software/HID/K95RGBPLATINUM.zip   0.2.7   FREYA_App_v1.07.123.bin         6d06b443cd85f4256d2b518b66b5c2d490d8089b678f9e34aecea97b13c5f5d4
  Corsair STRAFE            2.05 https://www3.corsair.com/software/HID/STRAFE.zip           0.2.7   STRAFE_APP_V205.bin             c03e6b2e3f5e3269f49d74e158fa9b65a4752dd7c888f0a9e96147033e18d243
  Corsair STRAFERGB         2.05 https://www3.corsair.com/software/HID/STRAFERGB.zip        0.2.7   STRAFERGB_APP_V205.bin          dff16fec9a0ae0d33aad0482f9ea02e3e55e231706b8c4e7fb66820aba98adc5
  Corsair M65RGB            2.04 https://www3.corsair.com/software/HID/M65RGB.zip           0.2.7   M65RGB_App_v204.bin             e1f09ce462f77071f91d92951410c14fb18061dd9760b3de89e45d1ca8b6b46c
  Corsair SCIMITARRGB       2.04 https://www3.corsair.com/software/HID/Scimitar.zip         0.2.7   SCIMITAR_APP_V204.bin           c17dcf20748c423e7c1116c081f88f5945d703126c813153d3407e61c65007fe

!END FW ENTRIES

!BEGIN NEW FW ENTRIES

# Vendor  Model             FW   URL                                                        Min.ckb File Name                       SHA256                                                              ProductID
  Corsair K70RGB            2.05 https://www3.corsair.com/software/HID/K70RGB.zip           0.2.7   K70RGB_APP_V205.bin             3e43bdcc5077dc413fbdee7ff6e57a978f758599142eef6979a96e3b8c3a566a    0x1b13
  Corsair K70LUX            2.04 https://www3.corsair.com/software/HID/K70LUX.zip           0.2.7   K70LUX_APP_V204.bin             c2b5411e1dce391788eca294563801b32a14bf7802eb29688213f8f07e112966    0x1b36
  Corsair K70LUXRGB         2.05 https://www3.corsair.com/software/HID/K70LUXRGB.zip        0.2.7   K70LUXRGB_APP_V205.bin          a1a0a4b2f74890eb708435b21ab197a301ea668269bca895f89f7301c354e83d    0x1b33
  Corsair K70RFIRE          2.05 https://www3.corsair.com/software/HID/K70RAPIDFIRE.zip     0.2.7   K70RAPIDFIRE_APP_V205.bin       6b1d2bb962ffd987ce5eb25c46b02a9069c5f79ca05d7b2cc71c749fe9813536    0x1b3a
  Corsair K70RFIRERGB       2.05 https://www3.corsair.com/software/HID/K70RGBRAPIDFIRE.zip  0.2.7   K70RGBRAPIDFIRE_APP_V205.bin    a5962bd1d890f5061fcf242fa8d3ca806913f899f37585d4367420aaded25104    0x1b38
  Corsair K95RGB            2.05 https://www3.corsair.com/software/HID/K95RGB.zip           0.2.7   K95RGB_APP_V205.bin             8d0680dd033d6020a53bc9bfa83e761143699d1122f1d0133e95ad3056d63a15    0x1b11
  Corsair K95PLATINUMRGB    1.07 https://www3.corsair.com/software/HID/K95RGBPLATINUM.zip   0.2.7   FREYA_App_v1.07.123.bin         6d06b443cd85f4256d2b518b66b5c2d490d8089b678f9e34aecea97b13c5f5d4    0x1b2d
  Corsair STRAFE            2.05 https://www3.corsair.com/software/HID/STRAFE.zip           0.2.7   STRAFE_APP_V205.bin             c03e6b2e3f5e3269f49d74e158fa9b65a4752dd7c888f0a9e96147033e18d243    0x1b15
  Corsair STRAFERGB         2.05 https://www3.corsair.com/software/HID/STRAFERGB.zip        0.2.7   STRAFERGB_APP_V205.bin          dff16fec9a0ae0d33aad0482f9ea02e3e55e231706b8c4e7fb66820aba98adc5    0x1b20
  Corsair M65RGB            2.04 https://www3.corsair.com/software/HID/M65RGB.zip           0.2.7   M65RGB_App_v204.bin             e1f09ce462f77071f91d92951410c14fb18061dd9760b3de89e45d1ca8b6b46c    0x1b12
  Corsair SCIMITARRGB       2.04 https://www3.corsair.com/software/HID/Scimitar.zip         0.2.7   SCIMITAR_APP_V204.bin           c17dcf20748c423e7c1116c081f88f5945d703126c813153d3407e61c65007fe    0x1b1e

!END NEW FW ENTRIES
-----BEGIN PGP SIGNATURE-----
```
Third way would be to handle the combination of line in FIRMWARE and productID with a separate file FIRMWARE-COMPATIBILITY, which could look like
```
# Model             ProductID
  K70RGB            0x1b13
  K70LUX            0x1b36
  K70LUXRGB         0x1b33
```
The last would be a headerfile with the same information as variant three above.
My favorite is the number one. Your opinion?

**Comment by tatokis** [comment]
Honestly, there's no point in trying to keep the fimrware update functionality in older versions, especially since it is broken for many users.

Chances are, corsair is going to release a new firmware that will break compatibility anyway, so the end user will have to update ckb anyway.

So no, I suggest we just switch to 8 columns, and leave old ckb versions without firmware updates.
Only thing we should look out for is to merge the PR only right before the release of a new version.

**Comment by frickler24** [comment]
Closing, because it is WiP.
Will be reopened later.

**Pull request closed without merging**
