### PR TITLE
Added newer model of K70

### PR DESCRIPTION
**Pull request by jannhama**
Newer 2016/2017 models of K70 have different product id. This is now added.

### CODE REVIEW

**Comment by hevanaa** [comment]
That id is used by K70 LUX (which I have). See https://github.com/ccMSC/ckb/pull/530

**Comment by hevanaa** [comment]
And you can't write a hex value as 0x0x (it is also wrong in the K70 value the line above).

**Comment by jannhama** [comment]
Thanks for pointing out, did it in hurry, now fixed.

**Comment by frickler24** [comment]
@jannhama and all K70xxx users: Because I'm fixing the FIRMWARE file currently via issue #26:
In the current VERSION control file only the K70RGB is mentioned.
What I found for K70LUX was a version file at [corsair(http://www3.corsair.com/software/HID/K70LUX.zip) with the current version file V2.04:
grafik

What I need to know is: 
1. Is that version number the same as you have?
2. Are there any other K70 Keyboards in use than K70RGB and K70LUX (e.g. K70 non rgb?)

**Comment by hevanaa** [comment]
1. That's exactly the firmware in use in my keyboard (K70 LUX  0x1B36). 

2. As far as I know, there are the following different K70 keyboards:

```
Name          id       as defined in src/ckb-daemon/usb.h
```
```
K70           0x1B09   P_K70_NRGB
K70 RGB       0x1B13   P_K70
K70 LUX RGB   0x1b33   P_K70_LUX
K70 LUX       0x1b36   P_K70_LUX_NRGB	 
K70 Rapidfire 0x1b38   P_K70_RFIRE
```

**Comment by tatokis** [comment]
There are also the k70 rapidfire keyboards, if I am not mistaken.

**Comment by hevanaa** [comment]
~~The K70 rapidfire usb ids are not yet added to the code then? Or am I wrong?~~

**Comment by hevanaa** [comment]
Ah, I was looking at the wrong branch

P_K70_RFIRE 0x1b38

Apparently this is an RGB variant.
Edit: updated post above with id.

**Comment by frickler24** [comment]
I added the most of the K70 firmware files /thanks for the list). 
The only one I can't find is the firmware for the K70 non-rgb.
Does anyone know the name of the zip-file for it?
It should be something like https://www3.corsair.com/software/HID/K70RGB.zip for the K70RGB.
I tried K70, K70NONRGB, K70NRGB.

**Comment by ghost** [comment]
@frickler24 although I did not manage to find a link for nor K70 neither K65 (both non-rgb, both from Vengeance series), here's a link for K70 Rapidfire (non-rgb): https://www3.corsair.com/software/HID/K70RAPIDFIRE.zip
Here's a link for K70 Rapidfire RGB:
https://www3.corsair.com/software/HID/K70RGBRAPIDFIRE.zip
The whole list of keyboards supported by CUE is:

> **Corsair Gaming and Vengeance K65/70/K95 RGB, K65/K70 LUX RGB, K65/K70 RGB RAPIDFIRE, K70 RAPIDFIRE, K70 LUX, STRAFE, and STRAFE RGB**

**Comment by jannhama** [comment]
@frickler24 How do you check current firmware version ?

**Comment by frickler24** [comment]
@jannhama I'm not sure whether I understand your question. Two possible answers:
- The current version in the viewpoint of corsair, it is that one you are able to download as default.
  Example K70RFIRE:
  The download link is always the same: [https://www3.corsair.com/software/HID/K70RAPIDFIRE.zip](https://www3.corsair.com/software/HID/K70RAPIDFIRE.zip)
  Download it, unzip it an have a look at the filename: 
  grafik
  K70RAPIFIRE_APP_V205.bin
The V205 is always the version number, we translate this to v2.05

- You can check your current firmware in the ckb client. For your gadget go to Device-panel, there you find your current rel-number:
grafik

**Comment by jannhama** [comment]
I've still older version of CKB installed so it cannot connect to keyboard.

**Comment by frickler24** [comment]
@jannhama what Version Do you have? My last m65rgb Version Running with ckb was a 1.x. Because of a bug  in the ckb I had to update manually. I don't assume that this is your problem.

**Comment by jannhama** [comment]
@frickler24 I think I had the base ckb version. Just compiled and installe ckb-next and keyboard is recognized. Firmware is 1.04 and it tells me there is an update but won't let me update (update fails)

**Comment by frickler24** [comment]
OK, two days ago @mattanger updated the master and testing branch with a new firmware file (I had the same problem as you and we fixed the issue).
So try to update your software and the client should be able to update to v2.04.

**Comment by jannhama** [comment]
Ok, will try tomorrow.

**Comment by koanya** [comment]
Hi,
My K70 rapidfire is not recognize (bought in 2016). The ID of my keyboard is 1b3a. I don't know why I have a different ID than the one on the list of @hevanaa. Maybe because it's an azerty keyboard.
Could you add it, please ? 
Thank you :)

**Comment by tatokis** [comment]
Is it an RGB model?

**Comment by koanya** [comment]
No, it's not an RGB model

**Comment by hevanaa** [comment]
Yes, someone need to add 
#define P_K70_RFIRE_NRGB 0x1b3a

**Comment by tatokis** [comment]
Alright, an update, as it has been almost 2 months now.
First of all, I'd like to thank you all for your time.

However, this PR only adds a single device in the list, which isn't that great as we have more devices not listed there.
I'll merge this for now, but an overhaul of the readme is due at some point.

**Pull request merged**
