### PR TITLE
Testing+issue97 k70 lux firmware update fails

### LINKED ISSUE #97: K70 LUX firmware update fails
I installed ckb-next-latest-git v0.2.4.r189.g8627b7e-1 on my Arch PC to update the firmware in my K70 LUX KB but it fails with error:
````
ckb-daemon[23557]: [E] fwupdate (firmware.c:78): Firmware file /tmp/ckb-13648-fwblob.bin doesn't match device (V: 1b1c P: 1b13)
````

Any suggestion?

Edit: I should add that the light strobing functions etc seem to work ok. It's only the firmware update function that I find does not work.

### PR DESCRIPTION
**Pull request by frickler24**
This PR is the first try to fix #97 . I Think, it should be marked as WiP and used carefully.
The K70 Lux should be detected correctly now (reason for #97).

One problem remains, which i cannot solve without more details:
The Firmware-list in FIRMWARE and that one in fwupgradedialog.cpp still differ.
fwupgradedialog.cpp checks before uploading, if it has the right file. it does so by checking for the hard coded (!!!) productIDs against  words 0x102, 0x104 and 0x106 in the firmware file loaded.
Here we should use the product ID given by the daemon now (it is a bit unsecure, because it may be manipulated by patching the file. So I did not implement it by now).

Here the problem mentioned: Some known hardware IDs are not in the one, some not in the other list.
If you reviewers agree, we should 
- test the PR by some of the users waiting for #97 
- publish the PR in testing, maybe with some more debugging info in fwupgradedialog.cpp
- wait for comments of other users.

Currently I'm thinking about a dialog you give a productID and get as answer what the client thinks what hardware, model (type), firmware-file and version number it detects and the reasons why.
Maybe the next days...

Happy easter!

### CODE REVIEW

**Comment by tatokis** [comment]
A bit late, but I am not sure if I like this implementation.

I think we should get rid of the hardcoded ids from fwupgradedialog.cpp, have dev IDs in the FIRMWARE file, and just check against that with the GUI.

Basically, the ckb GUI will handle picking the right file, and the daemon will only check the id inside the .bin file against the actual device, to make sure it's the right one.

**Comment by frickler24** [comment]
@tatokis The first test from @bulletmark shows that there is really an error in the implementation.
But what is your idea how the client should get the information, which device it handles?
The old way via interpreting the features has gone with K70.
There no 1:1 mapping anymore between features+names and ProductIDs.
We need the technical information from the daemon.

**Comment by tatokis** [comment]
Give me a moment, working on an implementation for the daemon.

**Comment by tatokis** [comment]
@frickler24 https://vps.tasossah.com/ckb-next/0001-daemon-expose-product-id-in-the-dev-nodes.patch
You can test it with `cat /dev/input/ckb1/productid`

We can have the GUI get the id from the daemon using the node, and then compare it against the FIRMWARE file which will have the IDs there.

**Comment by frickler24** [comment]
@tatokis OK, now it is in a separate file, before it was coupled with the firmware version file.
But that is not my problem (is it yours, that I appended the info to fwversion file?).
The real question is: Because of which criteria does the GUI select the correct line in FIRMWARE?

After the positive test from the K70RGB, I think we really need a mapping entry in FIRMWARE as we had in our  first discussion. Unfortunately, the FIRMWARE file then has to be re-signed with every minor modification. But then the choice is at least clear.

**Comment by tatokis** [comment]
@frickler24 Apologies, didn't notice that.
However, the product id is really not part of the firmware version, so I do think it should be separate.

Right, let me try to describe it better.
we modify the firmware file to something like this: 
```
Corsair K70RGB 2.05 https://www3.corsair.com/software/HID/K70RGB.zip 0.2.7 K70RGB_APP_V205.bin 3e43bdcc5077dc413fbdee7ff6e57a978f758599142eef6979a96e3b8c3a566a 1b13
```
Notice the product ID in the end of the line. This will be done for each device.

So from the beginning: The daemon initialises the device, exposes /dev/ckbX/productid with the ID of the device.
The GUI starts, wants to check the firmware version of the device.

It asks the daemon for its ID using /dev/ckbX/productid, then it fetches the FIRMWARE file.
It scans each line in FIRMWARE until it finds the matching productid, and then proceeds to check the version and everything else it currently does.

**Comment by frickler24** [comment]
I'm closing this one, because the new approach to fix this annoying bug is pushed in #220

**Pull request closed without merging**
