### PR TITLE
Add support for K70 Rapidfire (non-RGB) 0x1b3a

### PR DESCRIPTION
**Pull request by hevanaa**
This is now done against testing branch. I've also added the KB in question and the K70 LUX non-RGB to the IS_MONOCHROME macro. Hopefully this is correct.

### CODE REVIEW

**Comment by hevanaa** [comment]
Hmm, something went wrong there.

**Comment by hevanaa** [comment]
OK, think I solved the merge conflict (testing branch had changed after I forked it).

**Comment by tatokis** [comment]
From my understandint, the difference between a device being (!IS_RGB) or (IS_RGB && IS_MONOCHROME), is that the latter, while leveraging the RGB protocol, can allow for per-key lighting.
From Corsair's site I can see that both of these keyboard do support it, so we should be okay. Just need someone to test it.

Looks OK to me.

**Comment by hevanaa** [comment]
I've compiled and tested with my K70 LUX non-RGB. The Rainbow demo stopped working. The Trippy demo still worked. I guess the IS_MONOCHROME is no good then?

**Comment by hevanaa** [comment]
Couldn't get it to work at all with !IS_RGB. I'm removing them both from IS_MONOCHROME for now.

**Comment by hevanaa** [comment]
There must be some difference with the Strafe model (that has the IS_MONOCHROME macro) and at least this K70 LUX (non-RGB). Most things work in the GUI, except that pressing the Change Color button freezes the interface, but this happens both with if it is in IS_MONOCHROME and not (and it has always been like that with this model).

**Comment by tatokis** [comment]
```pressing the Change Color button freezes the interface``` That's a Qt bug, we have info about it in the readme.

**Comment by ghost** [comment]
Cross-reference to #86.

Works for @koanya who owns such keyboard. See https://github.com/mattanger/ckb-next/pull/55#issuecomment-282475982.

**Comment by tatokis** [comment]
My guess is these keyboards discard the colour packets, so it should be safe to add them for now.

**Pull request merged**
