### PR TITLE
Add `CMD/Shift+select` issue to Known Issues

### PR DESCRIPTION
**Pull request by fleischie**
This was a recommendation of @clodal in #29.

### CODE REVIEW

**Comment by ghost** [comment]
I guess it's more like not using ckb-next at all, not just stopping the daemon. Because it gets loaded every boot. However one can *unload* (and here must be a link to DAEMON.MD or just your own sentence on how to do this) it instead of *stop* and it won't. I also think this should be described in the other fashion, but somewhere else: people need to understand they really don't need this software for their devices to just work and can even have static lights if they save the profile to the hardware (this requires a newer version of the ckb-next with a fix by @frickler24). It is possible though that there exists a Corsair device that is not supported on Linux or macOS without this software but I highly doubt such device is on ours support list, so we shouldn't worry about this just for now. And on top of this all - s/Mac OS/macOS :)

**Comment by fleischie** [comment]
Amend changes regarding the known issue.

I contemplated but ultimately restrained from adding too much information for this one PR, as verbosely explaining the necessity of this project and what to expect with different device/OS combinations was outside of the intention of this PR. :wink:

**Comment by ghost** [comment]
Thanks. I don't have any more comments on this.

**Comment by ghost** [comment]
Since everyone is silent, I'll just merge. Feel free to revert/edit.

**Pull request merged**
